server:
  port: 8082

spring:
  application:
    name: Customer
  datasource:
    username: amigoscode
    password: password
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,mappings

